# Generated by Django 4.0.6 on 2022-07-29 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('appointment_end_time', models.TimeField()),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
